--- #YAML:1.0
name:                CGI-List
version:             0.03
abstract:            Easily generate HTML Lists From a DataBase
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Math::Round:                   0.01
    Number::Format:                0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - David Romero Garcia <romdav@gmail.com>
